name: Hello World Workflow

on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, World! My remote push"
          echo Add other actions to build,
          echo test, and deploy your project.
